//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 03. 21. 11:46:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Northwind
{
    public partial class Category {

        public Category()
        {
            this.Products = new List<Product>();
            OnCreated();
        }

        public virtual int CategoryID { get; set; }

        public virtual string CategoryName { get; set; }

        public virtual string Description { get; set; }

        public virtual byte[] Picture { get; set; }

        public virtual IList<Product> Products { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
