//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2021. 03. 21. 11:46:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Northwind
{
    public partial class Product {

        public Product()
        {
            this.UnitPrice = 0m;
            this.UnitsInStock = 0;
            this.UnitsOnOrder = 0;
            this.ReorderLevel = 0;
            OnCreated();
        }

        public virtual int ProductID { get; set; }

        public virtual string ProductName { get; set; }

        public virtual int? SupplierID { get; set; }

        public virtual int? CategoryID { get; set; }

        public virtual string QuantityPerUnit { get; set; }

        public virtual decimal? UnitPrice { get; set; }

        public virtual short? UnitsInStock { get; set; }

        public virtual short? UnitsOnOrder { get; set; }

        public virtual short? ReorderLevel { get; set; }

        public virtual bool Discontinued { get; set; }

        public virtual Category Category { get; set; }

        public virtual Supplier Supplier { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
